### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by SAStevens1** [Ole-Education/ESP#2]
Issue with Permissions: On the system admin role, I am adding users with their permissions.  The enable all function of the permissions works for the main categories, like course builder, but it doesn't automatically turn on the functions found in the drop down menus.  I'm turning those on by handFrom a perspective of how important this is to fix-it would be nice but in the meantime I can turn them on by hand and do not expect a bunch of new ones coming in.   You can fix it at your leisure.

- Marilyn

**Comment by josh-havens** [comment]
I believe this has been fixed. Please verify @marilynstefan.
